### ISSUE TITLE
Browser support or note should be updated for <section>

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#12]
The note mentions that Chrome supports as section role, and Firefox as a paragraph.

The later seems incorrect to me (a section is certainly not a paragraph, and usually contains multiple paragraphs plus other elements).

The former could be a typo, but if it isn't, there isn't a section role?

The spec says it should be mapped as a region (which maps to various things such as xml-roles:region or AXRoleDescription: 'region'), and discourages this if there is no accessible name (it isn't clear what it should map to if that is the case?)

Presumably Chrome/FF should be marked as partial or unsupported if they do not map to "region" or something related, or if they do, the note should be removed or updated.

**Comment by stevefaulkner** [comment]
> Presumably Chrome/FF should be marked as partial or unsupported if they do not map to "region" or something related, or if they do, the note should be removed or updated.

both expose xml-roles:region as is there is no iA2 role=region, for the purposes of AT, in this case the, that is the important bit. iA2 section is a generic role (has nothing to do with html5 section element). 

> and discourages this if there is no accessible name (it isn't clear what it should map to if that is the case?)

it normatively recommends AT do not announce `<section>` and consequently region without an accessible name as the `<section>` element is commonly misused as a replacement for `<div>`, it should still be exposed in acc layer as a region.
