### ISSUE TITLE
Should Chrome be partial for header?

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#14]
Assuming the header note is correct still, Chrome reports header as a section role, rather than banner (if the most root element). This seems incorrect and should be rated as partial, especially if there is no difference between the global page header and child headers (article headers, section headers, etc.)

**Comment by stevefaulkner** [comment]
@dstorey latest chrome reports as IA2_ROLE_HEADER, xml-roles:banner which is correct, so need to update note.
