### ISSUE TITLE
SVG logo broken in Safari on http://html5accessibility.com/html5elements/

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#15]
The size is too big:

![screen shot 2016-02-01 at 9 09 58 pm](https://cloud.githubusercontent.com/assets/465069/12740453/20b82970-c928-11e5-92e2-c2fb9c43c924.png)

Tested with Safari 9.

**Comment by stevefaulkner** [comment]
fixed, so is less broken, display is still kinda funky though 
https://github.com/stevefaulkner/HTML5accessibility/commit/78c3b6191009da49648f02ad5f54eb3c85f1e8ef
