### ISSUE TITLE
Enable datetime-local test?

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#16]
This element is supported by Chrome and Edge. It was removed from the W3C version of the spec but remains in the WHATWG version. We (Edge) implemented it because we wanted to be interoperable, and there is usage due to being in Chrome. No browser supports "datatime" (sans-local). My understanding is the local version has more use cases too and less problems, but I don't know the details myself.

When we do the work to firm up our date control accessibility to remove any rough edges, we'll be doing the same for datetime-local.

**Comment by stevefaulkner** [comment]
>Enable datetime-local test?

feel free to ;-)
