### ISSUE TITLE
Remove stray closing tags

### ISSUE THREAD

**Issue by powrsurg** [stevefaulkner/HTML5accessibility#27]
Validating the page shows that there are currently two stray closing tags. An extra `</td>` on line 582 (after the "Accessibility Support" for the `<video>`), and `</code>` on line 1357 after the 'menu' text for `<toolbar>`.

**Comment by dstorey** [comment]
Thanks! I didn't validate it until I got it on a public URL. Kinda amazed I only made 2 typos ;)
