### ISSUE TITLE
Missing BG images in WHCM

### ISSUE THREAD

**Issue by aardrian** [stevefaulkner/HTML5accessibility#28]
Some critical background images are missing when in Windows High Contrast Mode.
- browser logos at the top,
- feature support key.

I've added screen shots in IE11 on Windows 8 for each. I also added a screen shot of a border overlap in the footer.

I understand that in later versions of Edge background images will be displayed when a user is in Windows High Contrast Mode.

![virtualbox_ie11 - win8 1_21_04_2016_11_50_45](https://cloud.githubusercontent.com/assets/1376607/14715622/727c80bc-07b7-11e6-82d9-fefd945e6cde.png)
![virtualbox_ie11 - win8 1_21_04_2016_11_51_03](https://cloud.githubusercontent.com/assets/1376607/14715620/727b11b4-07b7-11e6-83b5-dc73177c4993.png)
![virtualbox_ie11 - win8 1_21_04_2016_11_51_16](https://cloud.githubusercontent.com/assets/1376607/14715621/727b5caa-07b7-11e6-9011-8942af6c4644.png)

**Comment by dstorey** [comment]
This has been heavily optimised for Windows 10 HC mode in Edge (and Mac HC mode, although there is nothing special I can add to target that). IE is now legacy for backwards compatibility with enterprise LOB apps for the most part. It is currently recommended for users of screen readers until MS Edge is ready, but that is getting close now.

**Comment by dstorey** [comment]
It is interesting that the border is showing in HC, as that was disabled using HC media queries, which should work in IE (the other adaptions like switching the expand button colour is being applied.

**Comment by dstorey** [comment]
I'm not so sure the browser icons at the top are critical considering there is text for the browser name, but I can probably get it back by disabling high contrast mode on the element. But this will probably create a whole can of worms for the bg/text colour, as I think it is on the parent. The key is probably easier to get back.

**Comment by stevefaulkner** [comment]
> I'm not so sure the browser icons at the top are critical considering there is text for the browser name

+1

**Comment by aardrian** [comment]
> > I'm not so sure the browser icons at the top are critical considering there is text for the browser name

> +1

Also agree. FWIW.
