### ISSUE TITLE
There is no date to indicate when testing was performed.

### ISSUE THREAD

**Issue by becka11y** [stevefaulkner/HTML5accessibility#36]
Someone sent me the following redesign url:  http://stevefaulkner.github.io/HTML5accessibility/.

I find it disturbing that there is no date when the testing was performed.  IMHO data is not useful unless one understand's the timeframe.  Steve's original page always included date information:
A work in progress: March 2016

Editors Draft march 7, 2016

WARNING! the data below is under continued revision

**Comment by dstorey** [comment]
I don't think this is needed any longer how compatible a browser engine is relates to the release version of the browser, not the date it was tested. Support doesn't change unless a new version comes out, but the versions tested are labelled. (or they will be when the redesign goes to master and the data is filled out. As the criteria has been clarified for each element, they all need updated.

To me the date tested just adds noise. You can find out if the date is needed for any reason by checking the github commits. That will say when the data was updated and which bits of data were updated.

**Comment by stevefaulkner** [comment]
I think, the important thing is the browser version that's been tested.

**Comment by stevefaulkner** [comment]
added month/year
