### ISSUE TITLE
Need icon to add to failing criteria (partial/no) with links

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#42]
Probably the icon is the same for both.

Suggestions:

* Link icon like the above, but more pretty (it has bad visual weight compared to others in github toolbar)
* A wee bug (this would be cuter, but then I link to platform status for missing features, which are kinda not bugs, so might need different icon for those if we went for a bug)

CC @melanierichards

**Comment by dstorey** [comment]
Depends on https://github.com/stevefaulkner/HTML5accessibility/pull/41 being merged (or can be added to that PR)

**Comment by melanierichards** [comment]
Was there supposed to be an image on this issue description? Still like the idea of a tiny arrow for this but we'll see.

**Comment by dstorey** [comment]
@melanierichards no, I was talking about the link icon on the GitHub toolbar when you write a comment
