### ISSUE TITLE
Update data for Firefox 46/Windows with new criteria

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#47]

**Comment by dstorey** [comment]
Group/Sectioning

Article: 

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* Can't find xml-roles:article but that is probably a failing of accProbe, which is the only tool I can get to work with Firefox.


Section:

Accessibly Supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* accRole (MSAA) is section, rather than landmark, but that might just be a IA2 difference. AccProbe is not showing IA2 values for Firefox even though it is enabled. xml-role is probably missing for same reason. Giving this a pass as accRole: section seems reasonable, but we should find some way to see the IA2 values.

Navigation: 

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* Same issue as others. AccRole (MSAA) of nav.

Aside: 

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* Same issue. AccName (MSAA) of aside.

Header: 

Accessibly supported: Partial?
Implemented: Yes
Mapped: Partial*
Name/Desc: Yes

* same issue as others. From the MSAA both root and not root get accRole of header, which I believe is wrong? But it could be that MSAA suppose to be the same and the IA2 one changes,

Footer: 

Accessibly supported: Partial?
Implemented: Yes
Mapped: Partial*
Name/Desc: Yes

*Same issue as header. accRole is footer for both. Could be that it is different in IA2

Figure:

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* same issue as others. MSAA role is correct for sure. Can't tell if IA2_RELATION_LABELLED_BY is set.

Figcaption:

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*

* same issue as before. MSAA of figcaption, so assuming it has IA2_ROLE_CAPTION but can't be sure. No idea if IA2_RELATION_LABEL_FOR is set.

Main: 

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* same as other landmarks. MSAA accRole is main, so assuming correct for now.

**Comment by dstorey** [comment]
Text-level

Time

Accessibly supported: Yes?
Implemented: Yes
Mapped: Yes?*
Name/Desc: Yes

* Can't test this as don't see IA2 but accRole is time. Can't see datetime attribute etc.

Mark

Accessibly supported: Partial
Implemented: Yes
Mapped: No*
Name/Desc: Partial

* same issue as others where can't see IA2. Only shows accRole mark if has aria (label/labelledby). Assume not supported as bug still open
* title not used as accName like it is for time and the spec.

**Comment by dstorey** [comment]
Graphics/Media

Canvas

Accessibly supported: Yes
Implemented: Yes.
ShowFocusIfNeeded: Yes
Mapped: Yes
SubDOM: Yes. 

Audio

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Keyboard: Yes*

* Yes, but spec only calls for grouping, rather than more specific like UIA
* Technically yes, but keyboard shortcuts are not discoverable

video

Accessibly supported: Partial
Implemented: Yes.
Mapped: Yes*
Keyboard: Partial*

* mapping is same as audio
* keyboard might work but is weird. Can't work out how to get to everything. Same as called out in existing test: https://bugzilla.mozilla.org/show_bug.cgi?id=494175

Track

Accessibly supported: Yes
Implemented: Yes
Subtitles: Yes (WebVTT only)

**Comment by dstorey** [comment]
Propertries

hidden:

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes

**required**:

Accessibly supported: Partial (could be yes if error works)
Implemented: Yes
Mapped: Yes*
Error: No*

* looks like this is setting the correct alert after submitting but don't see any status before submitting to show it is required. But looks like it is what the spec says.
* doesn't seem to be able to access error in Narrator and can't find any association with the error in accProbe but that could be failing of accProbe not showing IA2 correctly. Need to test with NVDA to be sure.

Placeholder:

Accessibly supported: Partial
Mapped: ?
Name/Desc: Partial*

* Can't see if there is a placeholder object attribute in accProbe
* aria-placeholder isn't used as accName when placeholder empty. Placeholder never used as accDesc (missing when label for/id is accName. Joined with label as accName when used with label wrapping input

**Comment by dstorey** [comment]
Controls

Search

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* Can't test mapping but expect hasn't regressed from previous test

*Tel *

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes

* Can't test mapping but expect hasn't regressed from previous test

*URL *

Accessibly supported: Partial
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes
Error state: Partial*

* Can't test mapping but expect hasn't regressed from previous test
* I think error states is partial as reads out alert but not the text in Narrator, but need to test NVDA

*Email *

Accessibly supported: Partial
Implemented: Yes
Mapped: Yes*
Name/Desc: Yes
Error state: Partial*

* Can't test mapping but expect hasn't regressed from previous test
* I think error states is partial as reads out alert but not the text in Narrator, but need to test NVDA

Datetime-local

N/A

Date

N/A

Month

N/A

Week

N/A

Time

N/A

Number

Accessibly supported: Partial
Implemented: Yes
Mapped: Yes
Name/Desc: Yes
Error state: Partial*
Keyboard: Yes*

* I think error states is partial as reads out alert but not the text in Narrator, but need to test NVDA
* keyboard works with up/down arrow rather than tabbing into arrows but i think this is correct (UI decision…anything a mouse user can access a keyboard user can too)

Range

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes 
Name/Desc: Yes
Keyboard; Yes


Color

Accessibly supported: Partial
Implemented: Yes
Mapped: Partial* 
Name/Desc: Yes
Keyboard; Partial*

* Mapping is same issue as current test. Button mapped but not value or association with dialog https://bugzilla.mozilla.org/show_bug.cgi?id=559767
* Can open colour dialog but not given focus so can't tab around it like can in chrome.

Datalist

Accessibly supported: Partial
Implemented: Yes
Mapped: Partial* 
Keyboard; Yes*

* the datalist is a list. I'm not 100% sure about the multiselect part as can't see it in accProbe but giving benefit of doubt as role is correct. However the attached input is basic text instead of combobox (which I think is MSAA so should show up). No idea about the other things, but failing that is enough for partial.

Output

Accessibly supported: Partial
Implemented: Yes
Mapped: Yes* 
Name/Desc: Partial*

* Assuming this is correct as marked as yes in current test and I know they;ve worked on it, but accProbe only shows role: text
* Partial name/desc as doesn't use label as accName id wrapping element rather than using for/id. Note: chrome disagrees in op-005 using contents for accName and title as accDesc. Spec sides with FF but is an open issue.

Progress

Accessibly supported: Yes
Implemented: Yes
Mapped: Yes* 
Name/Desc: Yes

* Can't see the mapping beyond progressBar (don't see readonly or any of the IA2 properties) but assume still correct from previous test

Meter

Accessibly supported: Partial
Implemented: Yes
Mapped: No?*
Name/Desc: Yes

* Could be accProbe issue but only mapped as DIV unless has aria (label/labelledby) when it maps to tag name. Assume properties are still missing like when last tested but can't see from the tool.

Details

N/A

Summary

N/A

Toolbar

Accessibly supported: No
Implemented: Yes
Mapped: No?*

* Spec says toolbar. Looks like it maps to plain "menu" but test could be wrong or accProbe not picking up correct things.

Context

Test not working, but claims support. I think it might only support old name. Need to check this.

Menuitem

Test not working, but claims support. I think it might only support old name. Need to check this.

Dialog

N/A

**Comment by dstorey** [comment]
There are a lot of assumptions as can't get IA2 to show in accProbe and nothing else is working in Firefox/Win 10, but this is a preliminary score based on those assumptions, and taking the existing scores for menu/context and menuitem as need to check the test for those:

X = 100 / (40 - 8) = 3.125 
Total = 100 - (1 * 3.125) - (14 * .5 * 3.125) = 75

**Comment by stevefaulkner** [comment]
> same issue as others. From the MSAA both root and not root get accRole of header, which I believe is wrong?

MSAA accrole is tagname regardless, makes no difference as this is legacy, non standard mapping and is not used by any AT AFAIK

**Comment by stevefaulkner** [comment]
>Menuitem
>Test not working, but claims support. I think it might only support old name. Need to check this.

checked and is mapped to menitem role

**Comment by dstorey** [comment]
I had some mistakes in the menu tests which are fixed now, so my assumptions there are not valid
