### ISSUE TITLE
Formalise partial/fail criteria now sub-criteria are listed

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#48]
Now we have sub-criteria it makes it more clear how a score is broken down. But we need to decide when something is a fail and when it is partial.

Most logical is if anything implemented has at least one partial then it gets an overall partial.

It could be argued that this increases scores if for example the mapping is a fail (old fail score) but part of the naming algorithm like aria-label is supported. This inflates Safari's score somewhat with new criteria (if my testing was correct), and will perhaps increase score for Edge 13 and IE11 (section elements upgraded to partial rather than fail. It is unlikely to improve Edge 14 score (actually more likely to decrease it as testing naming/desc allowed us to find a bunch of bugs). It could be better to require at least one pass in sub criteria to get a partial or no fails (e.g. all partials would get partial). This would be harder to understand though that something with a partial is not partial.

@stevefaulkner what do you think?

**Comment by stevefaulkner** [comment]
>Most logical is if anything implemented has at least one partial then it gets an overall partial.

I am good with this.
