### ISSUE TITLE
HTML5 features with Chrome bugs which are now "fixed"

### ISSUE THREAD

**Issue by MarcusJT** [stevefaulkner/HTML5accessibility#5]
The following HTML5 features listed at http://www.html5accessibility.com/ have chrome bugs listed & linked in the Notes column which when visited now have a status of "fixed" but need to be verified:
* datalist
* figcaption
* email input, search input, telephone input, URL input (already marked as fixed, surely that can be removed now) 
* output
* summary

**Comment by stevefaulkner** [comment]
have looked through, removed some
