### ISSUE TITLE
Update data for Safari 10 in macOS Sierra (10.12.x)

### ISSUE THREAD

**Issue by cookiecrook** [stevefaulkner/HTML5accessibility#59]
Update http://www.html5accessibility.com data for Safari 10 in macOS Sierra (10.12.x) and iOS 10.x

**Comment by cookiecrook** [comment]
@superarona or @sailingwave may be able to do this.

**Comment by stevefaulkner** [comment]
@cookiecrook updated to safari 11 high sierra
