### ISSUE TITLE
Multiple validation errors on html5accessibility.com homepage

### ISSUE THREAD

**Issue by dd8** [stevefaulkner/HTML5accessibility#65]
Looks like they're all caused by missing > before no:

```
<a href="https://developer.microsoft.com/en-us/microsoft-edge/platform/status/meterelement/"no</a>
```

**Comment by nschonni** [comment]
Fixed if you look at https://stevefaulkner.github.io/HTML5accessibility/, but I guess the `.com` is a separate webhost
