### ISSUE TITLE
`<time>`  reports as "not supported" in Chrome < 62

### ISSUE THREAD

**Issue by patrickhlauke** [stevefaulkner/HTML5accessibility#68]
Running https://thepaciellogroup.github.io/AT-browser-tests/test-files/time.html in current stable (60.x.x.x) Chrome (on Win, macOS, Android) the `<time>` element is shown as "not supported". However, quick test with TalkBack on Android confirms that it does indeed work correctly (e.g. in TM-001 is announces "October 28 2015, time").

From Chrome 62 onwards it is supported. Worth adding a note?

**Comment by stevefaulkner** [comment]
sure, what needs to be done is tests for safari need to be updated for latest, if you feel inclined that would be super fine!

**Comment by stevefaulkner** [comment]
sure, what needs to be done is tests for safari need to be updated for latest, if you feel inclined that would be super fine!

**Comment by nschonni** [comment]
Not sure if this helps
<img width="396" alt="screen shot 2017-09-22 at 1 01 20 am" src="https://user-images.githubusercontent.com/1297909/30730007-aad771ac-9f31-11e7-90ce-6a144b3a2b72.png">
<img width="774" alt="screen shot 2017-09-22 at 1 00 09 am" src="https://user-images.githubusercontent.com/1297909/30730008-aad7ecd6-9f31-11e7-9ebb-0870ae9bf7d8.png">

**Comment by stevefaulkner** [comment]
@nschonni  cheers

**Comment by stevefaulkner** [comment]
fixed
