### ISSUE TITLE
Firefox should be partial (or unsupported) for <video>

### ISSUE THREAD

**Issue by dstorey** [stevefaulkner/HTML5accessibility#8]
Note says "keyboard support suboptimal - cannot interact with individual controls. refer to Bug 494175"

This bug is still open. Not being able to interact with the feature via the keyboard is a fairly major accessibility issue. Presumably more so for people with motor issues. It at least shouldn't be considered fully supported.

**Comment by stevefaulkner** [comment]
@dstorey 

> Not being able to interact with the feature via the keyboard is a fairly major accessibility issue.

You can operate using a set of keyboard shortcuts, I think this is suboptimal as noted, but keyboard operation is implemented, just not easily discoverable :-( have pinged alex on bug to get update.

**Comment by stevefaulkner** [comment]
have changed to partially supported
