### ISSUE TITLE
Percentage calulation

### ISSUE THREAD

**Issue by DejfCold** [stevefaulkner/HTML5accessibility#83]
How is the percentage calculated?
Why does edge has 100% when it's missing 3 features?
If we count Partial and N/A as not supported it should be:

| Browser | Percentage |
| --- | --- |
| Chrome | 72.5% |
| Edge | 92.5% |
| FF | 67.5% |
| IE | 10% |
| Safari | 70% |

Whereas now it is: 

| Browser | Percentage |
| --- | --- |
| Chrome | 92% |
| Edge | 100% |
| FF | 89% |
| IE | 56% |
| Safari | 98% |

Which might be correct if N/A isn't considered in the calculation (haven't checked), but I'd argue if a feature is not applicable for some reason it should be considered as not supported.

**Comment by stevefaulkner** [comment]
I have been doing this site since 2011, I have always discounted features that are not implemented. i.e. not counted them in support percentages, as this site is about features whose accessibility mapping is supported by browsers, when are feature has been implemented.
