### ISSUE TITLE
Edge 80

### ISSUE THREAD

**Issue by 6523x** [stevefaulkner/HTML5accessibility#85]
Great Edge 80 is added but it doesn’t make sense to compare a browser released in 2020 to counterparts released in 2017, with FF being even a beta version.

Any chance the scores can be recalculated to a March or April 2020 baseline?

Seems a bit like cherry-picking results and I couldn’t help but notice design and development is in the hands of David Storey & Melanie Richards; both working for Microsoft.

**Comment by stevefaulkner** [comment]
> Any chance the scores can be recalculated to a March or April 2020 baseline?

am working on it, in meantime have set chrome/firefox/safari scores to ?
