### ISSUE TITLE
Missing data for Chrome and Safari?

### ISSUE THREAD

**Issue by dlockhart** [stevefaulkner/HTML5accessibility#90]
I noticed that with the recent updates in April, Chrome and Safari now only show "?" question marks in the summary table:

![Screen Shot 2020-05-20 at 1 01 33 PM](https://user-images.githubusercontent.com/5491151/82475150-0e132c00-9a9a-11ea-86b5-2a95b9f10795.png)

Was this intentional, or is there just some missing/pending data or tests that need to be run?

A year ago, support seemed pretty good:

![Screen Shot 2020-05-20 at 12 59 08 PM](https://user-images.githubusercontent.com/5491151/82475238-2f741800-9a9a-11ea-8b30-982da7564605.png)

I tried to manually calculate things based on the detailed tables below, but wasn't able to figure out how the existing numbers were achieved... I'm guessing it was based on what tests were available at the time the browser was last tested. Any info you could share would be appreciated!

**Comment by stevefaulkner** [comment]
fixed by #89
